spring:
  application:
    name: Account_Managment_Service
  datasource:
    url: jdbc:postgresql://localhost:5432/Account_Managment_DB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  mail:
    host: smtp.gmail.com
    port: 587
    username: mabroukyoussef10@gmail.com
    password: xowf cxna xzze lfxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

google:
  credentials:
    path: "src/main/resources/credentials.json"

server:
  port: 8999
