spring:
  application:
    name: Account_Managment_Service
  datasource:
    url: jdbc:postgresql://localhost:5432/Account_Managment_DB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop



eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

google:
  credentials:
    path: "src/main/resources/credentials.json"

server:
  port: 8999
